name: Unittests

on:
  pull_request:
    branches:
      - main
      - computer_vision
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        
      - name: System Dependencies installieren
        run: |
          sudo apt-get update
          # libcap-dev needed by python-prctl
          sudo apt-get install -y libcap-dev
          # libcamera C headers and shared libs
          sudo apt-get install -y libcamera-dev
          # Python 3 bindings for libcamera
          sudo apt-get install -y python3-libcamera
          # Optional: libcamera CLI tools
          sudo apt-get install -y libcamera-tools

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Python Abhängigkeiten installieren
        run: pip install -r ./computer_vision/requirements.txt
        working-directory: ${{ github.workspace }}
        
      - name: Unittests ausführen
        run: cd ./computer_vision && python -m unittest discover -s ./unit_tests -p "*_test.py"
