name: Unittests

on:
  pull_request:
    branches:
      - main
      - roboter
      - computer_vision
      - feat/pipeline
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Abhängigkeiten installieren
        run: |
          pip install -r ./computer_vision/requirements.txt

      - name: Unittests ausführen
        run: python -m unittest discover -s ./computer_vision/unit_tests -p "*_test.py"
