name: Unittests

on:
  pull_request:
    branches:
      - main
      - computer_vision
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        
      - name: System Dependencies installieren
        run: sudo apt-get update && sudo apt-get install -y libcap-dev

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Python Abhängigkeiten installieren
        run: pip install -r ./computer_vision/requirements.txt
        working-directory: ${{ github.workspace }}
        
      - name: Unittests ausführen
        run: cd ./computer_vision && python -m unittest discover -s ./unit_tests -p "*_test.py"
